### ISSUE TITLE
Multi-peer Checklist

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#1145]
This issue is intended to be a running checklist of several of the planned and necessary refactors in order to properly support efficient multi-peer parallel downloads.  It will be a multi-month effort and is being provided in order to help prevent duplication of effort and to avoid merge conflicts if anyone was also thinking of working in the referenced areas.

Given how drastic the overall changes will be, some of these will very likely need to be updated as the work proceeds since unexpected things invariably come up during large development efforts such as this.

- [ ] Refactor `CheckConnectBlock` to `CheckConnectBlockTemplate`
  - More accurately reflects its purpose of testing block template proposals and uses this fact to be more restrictive about the allowed inputs and to avoid performing the proof of work check.  In particular, the provided block template must only build from the current tip or its parent or an error should be returned.
- [ ] Convert to a full block index in memory
  - Since every block node will be in memory, the code which reconstructs headers from block nodes means that all headers will always be served from memory which will be important since the network will be moving to header-based semantics
  - Several of the error paths can be removed since they will no longer be necessary
  - It will no longer be expensive to calculate `CSV` sequence locks or median times of blocks way in the past
  - It will be much less expensive to calculate the initial states for the various intervals such as the stake and voter version
  - It will be possible to create much more efficient iteration and simplified views of the overall index
- [ ] Refactor and optimize checkpoint handling to use nodes instead of full blocks
  - Since the entire block index will be in memory, this code can be significantly optimized to use a node that is already in memory versus requiring the entire block
- [ ] Refactor and optimize block locator generation
  - The block locator code can be significantly optimized once the full block index is in memory since it will no longer be necessary to consult the database
- [ ] Refactor and optimized exported header access
  - Since headers can be reconstructed from a block index node and the full block index will be in memory, it will no longer be necessary to consult the database
- [ ] Refactor all code that relies on the main chain index in the database to use the new block index
  - This will be a major optimization for several functions because they will no longer have to first consult the database (which is incredibly slow in many cases due to the way `leveldb` splits all of the information across files) to perform lookups and determine if blocks are in the main chain
- [ ] Perform a database migration to remove the main chain index which will no longer be used
- [ ] Implement an efficient and well-tested chain view
  - Chain views can take advantage of the fact that all block nodes will be in memory to provide a flat view of a specific chain of blocks (a specific branch of the overall block tree) from a given tip all the way back to the genesis block
  - An example of some benefits are:
    - Efficiently comparing two views
	- Quickly finding the fork point (if any) between two views
	- O(1) lookups of nodes at a specific height
	- Possibility for more efficient block locator code through the use of the aforementioned O(1) height lookups
	- Possibility for efficient skip lists for ancestor iteration
- [ ] Refactor code to use the new chain view instead of manually tracking the best node
  - This will further speed up areas such as best chain selection, best chain membership testing, fork finding, and block locator generation
  - It will also simplify some of the more challenging parts of the code since it will more cleanly separate the chain-specific logic from th block index logic
- Refactor logic not specifically related to inputs out of `CheckTransactionInputs`
  - This will allow all sanity checks to be performed on blocks that do not yet connect due to arriving out of order in parallel
  - It will also reduce the time required to connect to the block to the best chain
- [ ] Change the UTXO view semantics to include the tip block unless it is disallowed by voters
  - The logic is currently backwards in that the current UTXO set does not include the tip block until it is approved by voters which leads to a plethora of undesirable behavior
  - This will allow all UTXO-related code to be significantly simplified
  - It optimizes for the typical case
  - It will fix issue #618
  - It will provide a path to more easily supporting a UTXO cache
- [ ] Add support to the block index for marking dirty nodes and flushing them to the database
  - This will allow validation states to be set on arbitrary nodes and persisted
- [ ] Implement a UTXO cache
  - Since connection is necessarily linear and all inputs reference previous outputs, performing the updates in memory with periodic writes to the database will allow intermediate states to effectively be skipped
- [ ] Decouple the chain processing and connection code from the download logic
  - This will ultimately allow blocks to be downloaded and stored based on the known headers even when all of the ancestors are not yet known
  - It will provide a path to remove orphan (unknown parents) handling from chain
  - It will allow the code related to the live tickets and UTXO set to be further simplified and optimized
- [ ] Remove all chain state from block manager
  - This will help ensure all of the chain-related state logic lives in the `blockchain` package
  - It will also provide a nice performance boost for various chain-state query functions since the block manager acts as a big lock
- [ ] Refactor the block manager to a `netsync` package
  - This will make it easier to add unit tests and paves the way for modifying the existing syncing logic
  - It will require several steps as well
  - [ ] Reduce the shared state between block manager and server
  - [ ] Introduce a config struct for block manager to decouple it from the main package config
  - [ ] Remove the dependency on `serverPeer`
- [ ] Rework the existing headers-first logic to download all of the headers instead of alternating based on checkpoints
  - This will allow the headers to be stored independently and ensure they all connect as well as providing all of the information needed to determine exactly which blocks comprise the chain with the most work without relying on checkpoints
- [ ] Rework the block download logic to use the newly available full header information while still being linear
  - This will break the reliance on blindly requesting newer blocks from peers
  - It will also pave the way towards implementing the logic necessary to request blocks from multiple peers
- [ ] Modify the block download logic to request blocks from multiple peers in parallel
  - This will also involve several steps such as keeping track of inflight blocks, re-requesting any data that has not been delivered after a certain time, weighting towards faster peers, and blacklisting misbehaving peers

**Comment by davecgh** [comment]
Updated description for PR #1229.

**Comment by davecgh** [comment]
Update issue description for PR #1230.

**Comment by davecgh** [comment]
Updated issue description for PR #1237.

**Comment by davecgh** [comment]
Update issue dscription for PR #1239.

**Comment by davecgh** [comment]
Update issue description for PR #1273.

**Comment by davecgh** [comment]
Updated issue description for PR #1332.

**Comment by davecgh** [comment]
Updated issue description for PR #1334.

**Comment by davecgh** [comment]
Update issue description for PR #1337.

**Comment by davecgh** [comment]
Updated issue description for PR #1344.

**Comment by davecgh** [comment]
Updated issue description for PR #1367.

**Comment by davecgh** [comment]
Updated issue description for PR #1375.

**Comment by davecgh** [comment]
Updated issue description for PRs #1452 and #1453.

**Comment by davecgh** [comment]
Updated issue description for PR #1457.

**Comment by davecgh** [comment]
Updated issue description for PR #1468.

**Comment by davecgh** [comment]
Updated issue description for PR #1500.

**Comment by davecgh** [comment]
Updated issue description for PRs #1471 and #1520.

**Comment by davecgh** [comment]
Updated issue description for PR #1728 and #1735.

**Comment by davecgh** [comment]
Updated issue description for PR #2497.

**Comment by davecgh** [comment]
Updated issue description for PR #2498.

**Comment by davecgh** [comment]
Updated issue description for PR #2499 and #2500.

**Comment by davecgh** [comment]
Updated issue description for PR #2518.

**Comment by davecgh** [comment]
Updated issue description for PR #2540.

**Comment by davecgh** [comment]
Updated issue description for PR #2555.

**Comment by davecgh** [comment]
Updated issue description for PR #2591.

**Comment by davecgh** [comment]
Updated issue description for PR #3443.

**Comment by davecgh** [comment]
Updated issue description for PR #3444.
